import React, { useRef, useEffect } from 'react';
import { Box, Dialog, DialogTitle, DialogContent, Button, Typography } from '@mui/material';
// Note: html2canvas must be installed in the project for image export to work:
// npm install html2canvas
import html2canvas from 'html2canvas';

export default function AgreementView({ open, onClose, assets = [], autoDownload = false }) {
  const ref = useRef();

  const handleDownload = async (format = 'png') => {
    if (!ref.current) return;
    // use html2canvas to capture as image
    try {
      const canvas = await html2canvas(ref.current, { backgroundColor: '#ffffff' });
      const mime = format === 'jpeg' ? 'image/jpeg' : 'image/png';
      const dataUrl = canvas.toDataURL(mime, 1.0);

      const a = document.createElement('a');
      a.href = dataUrl;
      a.download = `floodguard_agreement_${Date.now()}.${format}`;
      document.body.appendChild(a);
      a.click();
      a.remove();
    } catch (e) {
      console.error('Failed to generate image', e);
      alert('Failed to generate image. Please try opening the agreement and manually saving.');
    }
  };

  useEffect(() => {
    if (open && autoDownload) {
      // give dialog a moment to render then capture
      const t = setTimeout(() => {
        handleDownload('png').then(() => onClose && onClose());
      }, 400);
      return () => clearTimeout(t);
    }
  }, [open, autoDownload]);

  const totalValue = assets.reduce((s, a) => s + Number(a.value || 0), 0);

  return (
    <Dialog open={open} onClose={onClose} fullWidth maxWidth="md">
      <DialogTitle>Agreement / Asset Receipt</DialogTitle>
      <DialogContent>
        <Box ref={ref} sx={{ p: 3, bgcolor: '#fff' }}>
          <Box sx={{ textAlign: 'center', mb: 2 }}>
            <img src="/floodguard-logo.png.png" alt="logo" style={{ height: 60 }} />
            <Typography variant="h6" sx={{ mt: 1, fontWeight: 700 }}>FloodGuard Pakistan - Asset Agreement</Typography>
            <Typography variant="body2" color="text.secondary">Agreement / Receipt for Registered Assets</Typography>
          </Box>

          <Box sx={{ mt: 2 }}>
            <Typography variant="subtitle1" sx={{ fontWeight: 700, mb: 1 }}>Registered Assets</Typography>
            {assets.length === 0 ? (
              <Typography color="text.secondary">No assets registered.</Typography>
            ) : (
              <Box>
                {assets.map((a, i) => (
                  <Box key={i} sx={{ mb: 2, p: 2, border: '1px solid #e6e9ee', borderRadius: 1 }}>
                    <Typography sx={{ fontWeight: 700 }}>{a.name}</Typography>
                    <Typography variant="body2" color="text.secondary">Type: {a.type}</Typography>
                    <Typography variant="body2" color="text.secondary">Description: {a.description}</Typography>
                    <Typography variant="body2" color="text.secondary">Location: {a.location}</Typography>
                    <Typography variant="body2" color="text.secondary">Estimated Value: PKR {a.value}</Typography>
                  </Box>
                ))}

                <Box sx={{ mt: 2, p: 2, borderTop: '1px dashed #e6e9ee' }}>
                  <Typography variant="subtitle2">Total Assets: {assets.length}</Typography>
                  <Typography variant="subtitle2">Total Estimated Value: PKR {totalValue}</Typography>
                </Box>
              </Box>
            )}
          </Box>

          <Box sx={{ mt: 4, textAlign: 'center' }}>
            <Typography variant="caption" color="text.secondary">This agreement is generated by FloodGuard Pakistan. Please retain for your records.</Typography>
          </Box>

          <Box sx={{ mt: 6, borderTop: '1px solid #e6e9ee', pt: 1, textAlign: 'center' }}>
            <Typography variant="caption">flood guard 2025</Typography>
          </Box>
        </Box>

        <Box sx={{ display: 'flex', justifyContent: 'flex-end', gap: 2, mt: 2 }}>
          <Button onClick={() => handleDownload('png')} variant="outlined">Download PNG</Button>
          <Button onClick={() => handleDownload('jpeg')} variant="outlined">Download JPEG</Button>
          <Button onClick={onClose} variant="contained">Close</Button>
        </Box>
      </DialogContent>
    </Dialog>
  );
}
